### ISSUE TITLE
커밋 메세지에 대한 의견 제시

### ISSUE THREAD

**Issue by temtomk** [kevinpark2021/team3_wanted_onboarding#7]
## 커밋 메세지의 방향성에 대해서 의논해봅시다!

나중에 프로젝트가 복잡해지게 된다면 커밋 메세지가 통일 되어 있을 때 훨씬 알아보기가 쉬울 것 같습니다.

제가 주로 사용하는 커밋 메세지 양식을 먼저 소개해드리겠습니다.
> 추가 : [ADD]something
> 수정 : [UPDATE]something
> 삭제 : [DELETE]something

위의 양식을 한글로 해도 괜찮고 더 좋은 양식이 있다면 그것도 좋을 것 같습니다.

굳이 통일을 해야하냐는 의견도 괜찮습니다.

여러분들의 의견을 들려주세요!

**Comment by temtomk** [comment]
현재 이슈에 라벨을 설정하지 못합니다
아마 권한 문제인 것 같은데 팀장님이 한번 확인을 해주셔야 할 것 같습니다

**Comment by Aliasss** [comment]
이슈가 누적될수록 확인하기 어려워질 것 같아 말씀하신 것처럼 커밋 메시지를 통일하면 좋을 것 같습니다.

**Comment by taeyoonahn** [comment]
프로젝트를 함께 진행하면서 정말 중요한 것 중 하나가 통일된 양식 사용이라고 생각합니다.
정말 좋은 의견인것 같고 적극지지합니다!

커밋 이외에 다른 이슈에 대해서도 통일된 간단,명확한 양식을 빠르게 결정했으면 좋겠습니다.

**Comment by temtomk** [comment]
@taeyoonahn 커밋 이외의 다른 이슈에 대한 것도 통일시키자는 의견 굉장히 좋은 것 같습니다!

**Comment by kevinpark2021** [comment]
좋은 의견 감사합니다! 양식을 통일하거나 라벨을 생성하는 것으로 같이 논의해서 만들면 좋을 것 같습니다.

오늘 중으로 라벨 생성 해보고 공유드릴게요!

**Comment by kevinpark2021** [comment]
5.2 회의 내용
- 기존의 태민님 양식을 축으로 하되, 개인적으로 커스텀 가능 (단 커스텀 하기 전 팀원 전체에게 공지하고 승인 받은 뒤 사용)
- 커스텀 전 태민님이 올려주신 커밋메시지 리스트 참고
- 수정 사항을 노트북 파일 상단에 markdown으로 달아놓기

**Comment by temtomk** [comment]
커밋 양식 이슈 재등록
